### PR TITLE
Fetch data from wikipedia.org

### LINKED ISSUE #44: Standardize Encodings
The inconsistencies in encoding are getting quite difficult to deal with. See #41 for an example -- `get_meta_infobox('<TEMPLATE_NAME>').rendered_keys()` is returning a mix of what are Unicode types (with `u` prefix), and normal string types (without the `u` prefix). And further, the newest change, as I mentioned in #41, is that the `u` prefixed strings are what actually should be normal strings that are encoded in utf-8. For example, `'rate': u'Rate\xa0of\xa0fire'` should actually be `'rate': 'Rate\xa0of\xa0fire'` (note the lack of `u`) since '\xc2\xa0' is a utf-8 encoded string. When decoded, it yields a Unicode string u'\xa0':
```Python
>>> 'Rate\xc2\xa0of\xc2\xa0fire'.decode('utf8')
u'Rate\xa0of\xa0fire'
```
Which then yields a proper Unicode string, which can be dealt with accordingly with `unidecode`:
```Python
>>> unidecode(u'Rate\xa0of\xa0fire')
'Rate of fire'
```

I propose that all strings are of the normal Python string type, just encoded in utf-8 (meaning `'Rate\xc2\xa0of\xc2\xa0fire'` instead of `u'Rate\xc2\xa0of\xc2\xa0fire'`). This way, no information is lost, such as when it is transliterated using `unidecode`, and in the case that someone wants to transliterate it, it is possible to use unidecode without unexpected errors (see #41).

I would fix this myself, but I am having trouble wrapping my mind around why things are encoded and decoded in the code, such as in `fetcher.py`, `persistentkv.py`, and `renderer.py`, and I have no idea how one managed to get `u'Rate\xc2\xa0of\xc2\xa0fire'` instead of `'Rate\xc2\xa0of\xc2\xa0fire'`. Thoughts?

### PR DESCRIPTION
**Pull request by alvaromorales**
Added a fetcher and renderer that fetches data directly from wikipedia.org (see #31). Implemented a CachingFetcher and CachingRenderer as proposed in #46.

I read the [FAQ](https://www.mediawiki.org/wiki/API:FAQ#get_the_content_of_a_page_.28wikitext.29.3F) on the Wikipedia API and ran experiments to determine the fastest way to get rendered and unrendered pages. I experimented with /index.php, /api.php, and RESTbase, and found that index.php was best for the Fetcher and api.php was best for the renderer.

Also fixed #44 -- all strings in WikipediaBase are now unicode, except when outputting an enchantment for START.

Unfortunately, this ended up being a *huge* change that broke several tests. I was unable to just swap out the implementation of the old WikipediaSiteFetcher because other abstractions like Article or Infobox made assumptions on the format of the data returned by the Fetcher. Wikipedia.org's data was different enough to break some regexes or XPATH expressions.

Apologies for the size of this PR, but I found some bugs along the way that needed to be fixed to get tests to pass.

### CODE REVIEW

**Comment by alvaromorales** [comment]
Build failed because of #48. @fakedrake could you restart the build on Travis?

**Comment by michaelsilver** [comment]
I'm surprised that you use the human-visitable, real Wikipedia website to get pages -- won't you get banned? I think @fakedrake said that when he last tried this he got banned. Or, do you have some sort of request limit in place that prevents that from happening?

I agree that we should not "push the limits" with the API, but the API is designed for this kind of stuff (computers are fast, whoever made the API realizes this).

**Comment by alvaromorales** [comment]
Valid point; I'd be willing to switch back to using the Wikipedia API if we think it's better (that's what I first started working on). Especially if @fakedrake did indeed get banned.

As to why I chose /index.php:

1) I assumed that the same usage guidelines applied (serial requests are fine). 

2) The [API FAQ guidelines](https://www.mediawiki.org/wiki/API:FAQ#get_the_content_of_a_page_.28wikitext.29.3F) encourage it:

> If you just want the raw wikitext without any other information whatsoever, it's best to use index.php's action=raw mode instead of the API

> If you just want the HTML, it's best to use index.php's action=render mode instead of the API

3) I ran experiments and got better performance using index.php. 

The results below show the total time to fetch 41 articles.

```
Using /index.php
    source: 4.87s
    rendered: 4.87s

Using /api.php
    source: 5.40s
    rendered: 26.46s
```

**Comment by fakedrake** [comment]
I did get banned from wikipedia but not entirely:
https://github.com/fakedrake/WikipediaBase/issues/21.

So we can't switch to wikipedia.org for renderer.py but I have no good
argument against using it for everything else unless we start crawling
wikipedia or something.

Another point that can be made is that renderer.py only renders meta
infoboxes. That means that it might be doable to have it cache every single
infobox type from ashmore and never have it access the internet again. Then
we use fast wikipedia.org for everything and everyone is (probably) happy.

Right now I am on vacation/business trip but I have been loosely working on
a mechanism to control global configuration at a single point (config
branch) so if everything works out as I picture it, eventually tests that
won't need to go out to the internet at all, and we will be able to decide
on what source the production should use whenever we want. And even switch
back and forth at runtime if needed.

On Sun, Aug 9, 2015 at 12:35 AM, Alvaro Morales <notifications@github.com>
wrote:

> Valid point; I'd be willing to switch back to using the Wikipedia API if
> we think it's better (that's what I first started working on). Especially
> if @fakedrake <https://github.com/fakedrake> did indeed get banned.
>
> As to why I chose /index.php:
>
> 1) I assumed that the same usage guidelines applied (serial requests are
> fine).
>
> 2) The API FAQ guidelines
> <https://www.mediawiki.org/wiki/API:FAQ#get_the_content_of_a_page_.28wikitext.29.3F>
> encourage it:
>
> If you just want the raw wikitext without any other information
> whatsoever, it's best to use index.php's action=raw mode instead of the API
>
> If you just want the HTML, it's best to use index.php's action=render mode
> instead of the API
>
> 3) I ran experiments and got better performance using index.php.
>
> The results below show the total time to fetch 41 articles.
>
> Using /index.php
>     source: 4.87s
>     rendered: 4.87s
>
> Using /api.php
>     source: 5.40s
>     rendered: 26.46s
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fakedrake/WikipediaBase/pull/47#issuecomment-129046412>
> .
>



-- 
Chris Perivolaropoulos

**Comment by alvaromorales** [comment]
Ah, yes the sandbox feature (editing articles) is more heavily restricted. But the renderer in this PR uses the Wikipedia API, which allows us to make serial requests (rendering included).

If it's ever a problem, though, I agree that we could fall back to ashmore.

Let me know when you get a chance to review this; I'll work on increasing test coverage next.

**Comment by alvaromorales** [comment]
Just wanted to follow up on this. @fakedrake can you take a look when you have a sec?

**Comment by fakedrake** [comment]
Yes sorry, I took a quick look at it as I am not at home. I trust that it's ok :)

**Comment by alvaromorales** [comment]
Thanks! Feel free to assign me any issues in the future if you would like any changes. Hope you're enjoying the vacation/business trip :-)

**Pull request merged**
